# Use an OpenJDK base image
FROM openjdk:23-slim

# Copy necessary files
COPY Bonus.jar /app/Bonus.jar

# Set the working directory
WORKDIR /app

# Command to run the application
CMD ["java", "-jar", "Bonus.jar"]

