apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-station
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-station
  template:
    metadata:
      labels:
        app: central-station
    spec:
      containers:
      - name: central-station
        image: central-station:latest
        imagePullPolicy: Never
        env:
        - name: KAFKA_BROKER_URL
          value: "kafka:9092"
        - name: BITCASK_DIRECTORY
          value: "/data/bitcask"
        - name: PARQUET_OUTPUT_PATH
          value: "/data/parquet"
        volumeMounts:
        - mountPath: /data
          name: shared-storage
      volumes:
      - name: shared-storage
        persistentVolumeClaim:
          claimName: shared-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: central-station
spec:
  selector:
    app: central-station
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080