apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: elastic-kibana
  name: elastic-kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elastic-kibana
  template:
    metadata:
      labels:
        app: elastic-kibana
    spec:
      hostname: elastic-kibana
      containers:
      - image: nshou/elasticsearch-kibana
        imagePullPolicy: Never
        name: elastic-kibana
        ports:
          - containerPort: 9200  # Elasticsearch HTTP port
          - containerPort: 5601  # Kibana port
        volumeMounts:
          - name: shared-volume
            mountPath: /home/data/parquet
      volumes:
        - name: shared-volume