apiVersion: v1
kind: Service
metadata:
  name: es-indexer
spec:
  selector:
    app: es-indexer
  ports:
  - name: http
    port: 80
    targetPort: 8080
  type: ClusterIP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-indexer
spec:
  selector:
    matchLabels:
      app: es-indexer
  replicas: 1
  template:
    metadata:
      labels:
        app: es-indexer
    spec:
      containers:
      - name: es-indexer
        image: es-indexer:latest
        imagePullPolicy: Never
        env:
          - name: ES_SERVER
            value: "http://elasticsearch:9200"
        volumeMounts: 
        - name: shared-volume
          mountPath: /home/data
      volumes: 
      - name: shared-volume
        persistentVolumeClaim:
          claimName: shared-volume