apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-indexer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es-indexer
  template:
    metadata:
      labels:
        app: es-indexer
    spec:
      containers:
      - name: es-indexer
        image: es-indexer:latest
        imagePullPolicy: Never
        env:
        - name: ELASTICSEARCH_HOST
          value: "elasticsearch"
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: PARQUET_DIRECTORY
          value: "/home/data/parquet"
        volumeMounts:
        - mountPath: /home/data/parquet
          name: shared-volume
      volumes:
      - name: shared-volume
        persistentVolumeClaim:
          claimName: shared-volume