apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station-1
  template:
    metadata:
      labels:
        app: weather-station-1
    spec:
      containers:
      - name: weather-station-1
        image: weather-station:latest
        imagePullPolicy: Never
        env:
        - name: STATION_ID
          value: "1"
        - name: KAFKA_BROKER_URL
          value: "kafka:9092"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: weather-station-1
spec:
  selector:
    app: weather-station-1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station-2
  template:
    metadata:
      labels:
        app: weather-station-2
    spec:
      containers:
      - name: weather-station-2
        image: weather-station:latest
        imagePullPolicy: Never
        env:
        - name: STATION_ID
          value: "2"
        - name: KAFKA_BROKER_URL
          value: "kafka:9092"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: weather-station-2
spec:
  selector:
    app: weather-station-2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
