apiVersion: v1
kind: Namespace
metadata:
  name: weather-monitoring-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station
spec:
  replicas: 10
  selector:
    matchLabels:
      app: weather-station
  template:
    metadata:
      labels:
        app: weather-station
    spec:
      containers:
      - name: weather-station
        imagePullPolicy: Never
        image: weather-station
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_SERVER
          value: "kafka-service:9092"

---

apiVersion: v1
kind: Service
metadata:
  name: weather-station-service
spec:
  selector:
    app: weather-station
  ports:
    - protocol: TCP
      port: 8080

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-base-station
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-base-station
  template:
    metadata:
      labels:
        app: central-base-station
    spec:
      containers:
      - name: central-base-station
        image: central-server
        ports:
        - containerPort: 8080
        env:
        - name: KAFKA_SERVER
          value: "kafka-service:9092"
        - name: ELASTICSEARCH_URL
          value: "http://elasticsearch-service:9200"

---

apiVersion: v1
kind: Service
metadata:
  name: central-base-station-service
spec:
  selector:
    app: central-base-station
  ports:
    - protocol: TCP
      port: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092

---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  selector:
    app: zookeeper
  ports:
    - protocol: TCP
      port: 2181

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-kibana
  template:
    metadata:
      labels:
        app: elasticsearch-kibana
    spec:
      containers:
      - name: elasticsearch-kibana
        image: nshou/elasticsearch-kibana:latest
        ports:
        - containerPort: 5601
        - containerPort: 9200

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-kibana-service
spec:
  selector:
    app: elasticsearch-kibana
  ports:
    - protocol: TCP
      port: 5601
      name: kibana-port
    - protocol: TCP
      port: 9200
      name: elasticsearch-port

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: weather-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/weather-data"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weather-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      type: local