apiVersion: v1
kind: PersistentVolume
metadata:
  name: shared-volume
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-volume
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  ports:
    - port: 2181
      name: client
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  serviceName: "zookeeper"
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: bitnami/zookeeper:latest
        imagePullPolicy: Never
        env:
          - name: ALLOW_ANONYMOUS_LOGIN
            value: "yes"
        ports:
          - containerPort: 2181
            name: client
        volumeMounts:
          - name: data
            mountPath: /bitnami/zookeeper
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  ports:
    - port: 9092
      name: kafka
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app: kafka
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        imagePullPolicy: Never
        env:
        - name: ALLOW_PLAINTEXT_LISTENER
          value: "yes"
        - name: KAFKA_BROKER_ID
          value: "0"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KAFKA_LISTENERS
          value: PLAINTEXT://:9092
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://$(POD_IP):9092
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zookeeper:2181
        ports:
        - containerPort: 9092
          name: kafka
        volumeMounts:
        - name: shared-volume
          mountPath: /data/kafka
  volumeClaimTemplates:
  - metadata:
      name: shared-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: central-station
spec:
  replicas: 1
  selector:
    matchLabels:
      app: central-station
  template:
    metadata:
      labels:
        app: central-station
    spec:
      containers:
      - name: central-station
        image: central-station:latest
        imagePullPolicy: Never
        env:
        - name: KAFKA_BROKER_URL
          value: "kafka:9092"
        - name: BITCASK_DIRECTORY
          value: "/data/bitcask"
        - name: PARQUET_OUTPUT_PATH
          value: "/data/parquet"
        volumeMounts:
        - mountPath: /data
          name: shared-volume
      volumes:
      - name: shared-volume
        persistentVolumeClaim:
          claimName: shared-volume
---
apiVersion: v1
kind: Service
metadata:
  name: central-station
spec:
  selector:
    app: central-station
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station-1
  template:
    metadata:
      labels:
        app: weather-station-1
    spec:
      containers:
      - name: weather-station-1
        image: weather-station:latest
        imagePullPolicy: Never
        env:
        - name: STATION_ID
          value: "1"
        - name: KAFKA_BROKER_URL
          value: "kafka:9092"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: weather-station-1
spec:
  selector:
    app: weather-station-1
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station-2
  template:
    metadata:
      labels:
        app: weather-station-2
    spec:
      containers:
      - name: weather-station-2
        image: weather-station:latest
        imagePullPolicy: Never
        env:
        - name: STATION_ID
          value: "2"
        - name: KAFKA_BROKER_URL
          value: "kafka:9092"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: weather-station-2
spec:
  selector:
    app: weather-station-2
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station-3
  template:
    metadata:
      labels:
        app: weather-station-3
    spec:
      containers:
      - name: weather-station-3
        image: weather-station:latest
        imagePullPolicy: Never
        env:
        - name: STATION_ID
          value: "3"
        - name: KAFKA_BROKER_URL
          value: "kafka:9092"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: weather-station-3
spec:
  selector:
    app: weather-station-3
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station-4
  template:
    metadata:
      labels:
        app: weather-station-4
    spec:
      containers:
      - name: weather-station-4
        image: weather-station:latest
        imagePullPolicy: Never
        env:
        - name: STATION_ID
          value: "4"
        - name: KAFKA_BROKER_URL
          value: "kafka:9092"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: weather-station-4
spec:
  selector:
    app: weather-station-4
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station-5
  template:
    metadata:
      labels:
        app: weather-station-5
    spec:
      containers:
      - name: weather-station-5
        image: weather-station:latest
        imagePullPolicy: Never
        env:
        - name: STATION_ID
          value: "5"
        - name: KAFKA_BROKER_URL
          value: "kafka:9092"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: weather-station-5
spec:
  selector:
    app: weather-station-5
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-6
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station-6
  template:
    metadata:
      labels:
        app: weather-station-6
    spec:
      containers:
      - name: weather-station-6
        image: weather-station:latest
        imagePullPolicy: Never
        env:
        - name: STATION_ID
          value: "6"
        - name: KAFKA_BROKER_URL
          value: "kafka:9092"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: weather-station-6
spec:
  selector:
    app: weather-station-6
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-7
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station-7
  template:
    metadata:
      labels:
        app: weather-station-7
    spec:
      containers:
      - name: weather-station-7
        image: weather-station:latest
        imagePullPolicy: Never
        env:
        - name: STATION_ID
          value: "7"
        - name: KAFKA_BROKER_URL
          value: "kafka:9092"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: weather-station-7
spec:
  selector:
    app: weather-station-7
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station-8
  template:
    metadata:
      labels:
        app: weather-station-8
    spec:
      containers:
      - name: weather-station-8
        image: weather-station:latest
        imagePullPolicy: Never
        env:
        - name: STATION_ID
          value: "8"
        - name: KAFKA_BROKER_URL
          value: "kafka:9092"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: weather-station-8
spec:
  selector:
    app: weather-station-8
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-9
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station-9
  template:
    metadata:
      labels:
        app: weather-station-9
    spec:
      containers:
      - name: weather-station-9
        image: weather-station:latest
        imagePullPolicy: Never
        env:
        - name: STATION_ID
          value: "9"
        - name: KAFKA_BROKER_URL
          value: "kafka:9092"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: weather-station-9
spec:
  selector:
    app: weather-station-9
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-station-10
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-station-10
  template:
    metadata:
      labels:
        app: weather-station-10
    spec:
      containers:
      - name: weather-station-10
        image: weather-station:latest
        imagePullPolicy: Never
        env:
        - name: STATION_ID
          value: "10"
        - name: KAFKA_BROKER_URL
          value: "kafka:9092"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: weather-station-10
spec:
  selector:
    app: weather-station-10
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
